### ISSUE TITLE
2D Image Space to 3D World Coordinate Space

### ISSUE THREAD

**Issue by prachi-shahi** [christian-rncl/TrackNPred#8]
Hi,

I need to see how you've implemented the 2D image space to the 3D world coordinate space conversion in TraPHic. Where exactly (which file, which lines) is this happening?

Thank you!

**Comment by ChaofanTao** [comment]
I am also wondering the way of coordinate convertion. Please tell me if someone has ideas. Thank you.

**Comment by rohanchandra30** [comment]
We used the camera matrices corresponding to the camera used for recording the videos in the TRAF dataset. It is not included in the code I believe. I will release the camera matrices and corresponding code for conversion on the github page

**Comment by ChaofanTao** [comment]
Thank you very much. I am looking forward to the code!


Rohan Chandra <notifications@github.com> 于2019年9月18日周三 下午5:08写道：

**Comment by rohanchandra30** [comment]
I added the 2D to 3D conversion script in the main level. Go through it and let me know if you have any questions.

**Comment by rohanchandra30** [comment]
#

**Comment by ChaofanTao** [comment]
Thanks for the script. I do not have questions about the conversion yet, but I have a little questions about the released dataset TRAF (https://drive.google.com/drive/folders/1LFK3H-GWiHWVfu_UPYJAnezt7IH0hhUJ).
Some files are not as organized as the description in the README. For example, TRAF22_gt.txt does not contains the classID; TRAF15_gt.txt contains unknown classes like desk or object. 

I want to know how do you face this problem in the Paper "TraPHic", since I want to follow your data, try to use this kind of heterogeneous traffic data in my work.

**Comment by rohanchandra30** [comment]
We did not use all the TRAF videos in the paper.
